name: artwork_puzzle_pieces_api
description: The interface and models for an API providing access to artwork puzzle pieces.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
#  meta: ^1.7.0
#  rxdart: ^0.27.3
#  shared_preferences: ^2.0.13
#  todos_api:
#    path: ../todos_api
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
