name: squaresplitter
description: A utility package to split images in a grid pattern
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  image: ^3.1.3
  tuple: ^2.0.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
