name: artwork_puzzle_pieces_repository
description: A repository that handles artwork split images related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
#  firebase_core: ^0.4.2+2
#  firebase_storage: ^3.1.6
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  squaresplitter:
    path: ../squaresplitter
  tuple: ^2.0.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
